shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('shop/', views.list_item, name='list_item'),
    path('shop/<int:item_id>/detail/', views.detail_item, name='detail_item'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')

    def __str__(self):
        return f'Name: {self.name}'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    price = models.IntegerField(default=0, verbose_name='Price')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category')
    bought = models.BooleanField(verbose_name='Bought')
    date = models.DateField(auto_now=True, verbose_name='Date')

    def __str__(self):
        return f'Name: {self.name} - Price: {self.price} - Category: {self.category} - Bought: {self.bought}' \
               f' - Date: {self.date}'

shop/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=30, verbose_name='Name')
    price = models.IntegerField(default=0, verbose_name='Price')

    def __str__(self):
        return f' Name: {self.name} - Price: {self.price}'


class Purchase(models.Model):
    name = models.CharField(max_length=30, verbose_name='Name')
    age = models.IntegerField(default=0, verbose_name='Age')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='Item')

    def __str__(self):
        return f'Name: {self.name} - Age: {self.age} - Item: {self.item_id}'

catalog/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Item, Purchase


def list_item(request):
    item_list = Item.objects.all()
    context = {
        'items': item_list
    }
    return render(request, 'list_item.html', context)


def detail_item(request, item_id):
    detail_item_list = get_object_or_404(Item, id=item_id)
    context = {
        'items': detail_item_list
    }
    return render(request, 'detail_item.html', context)

shop/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  {% if current_user.is_authenticated %}
  {{ current_user.username }}
  {% endif %}
  {% block content %}
  {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

shop/templates/detail_item.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="margin-top: 50px">
    <h3 class="text-center" style="margin-bottom: 30px">Item detail</h3>
    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Buyer's name</th>
      <th scope="col">Age</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <th scope="row">{{items.id}}</th>
        <td>{{ items.name }}</td>
        <td>{{ items.price }}</td>
        {% for item in items.purchase_set.all %}
        <td>{{ item.name }}</td>
        <td>{{ item.age }}</td>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}

shop/templates/list_item.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="margin-top: 50px">
    <h3 class="text-center" style="margin-bottom: 30px">Item list</h3>
    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
{% for item in items %}
        <tr>
            <th scope="row">{{item.id}}</th>
            <td>{{ item.name }}</td>
        <td>{{ item.price }}</td>
        </tr>
{% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}